<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Frontend\Dashboard\Module'                         => __DIR__ . '/Module.php',
  'Frontend\Dashboard\Controller\DashboardController' => __DIR__ . '/src/Frontend/Dashboard/Controller/DashboardController.php',
);
