<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Frontend\Login\Module'                     => __DIR__ . '/Module.php',
  'Frontend\Login\Controller\LoginController' => __DIR__ . '/src/Frontend/Login/Controller/LoginController.php',
  'Frontend\Login\Form\Filter\Register'       => __DIR__ . '/src/Frontend/Login/Form/Filter/Register.php',
  'Frontend\Login\Form\Login'                 => __DIR__ . '/src/Frontend/Login/Form/Login.php',
  'Frontend\Login\Form\Register'              => __DIR__ . '/src/Frontend/Login/Form/Register.php',
);
