<?php echo $this->doctype('HTML5') ?>
<?php $this->plugin('translate')->setTranslatorTextDomain('administration'); ?>
<html lang="de">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php
    // titel
    echo $this->headtitle('TITLE_STARTSEITE', 'APPEND')
        ->setAutoEscape(true)
        ->setSeparator(' » ');

    echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');


    $this->headScript()
        ->appendFile('//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js')
        ->appendFile('//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js')
        ->appendFile($this->basePath() . '/js/frontend/jquery.modal.js')
        ->prependFile($this->basePath() . '/js/frontend/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/frontend/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',));

    // css
    echo $this->headLink()
        ->appendStylesheet('//netdna.bootstrapcdn.com/bootswatch/3.1.1/yeti/bootstrap.min.css')
        ->appendStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,300,700')
        ->appendStylesheet('//fonts.googleapis.com/css?family=Lato:400,700')
        ->appendStylesheet('//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css')
        ->appendStylesheet($this->basePath() . '/css/frontend/jquery.modal.css')
        ->appendStylesheet($this->basePath() . '/css/frontend/style.css');

    ?>
</head>
<body>
    <nav class="navbar navbar-default navbar-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->basePath('/'); ?>">
                    <img width="60px" src="<?php echo $this->basePath('images/frontend/Arma3_Trans_Logo.png') ?>" alt="Arma"/>
                    <?php echo $this->translate('Arma Squad XML Hoster') ?>
                </a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li class="navbar-brand">
                        <?php echo sprintf($this->translate('Welcome back, <b>%s</b>!'), $this->identity()->username); ?>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Userpanel <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url('frontend/user/home'); ?>"><?php echo $this->translate('Home'); ?></a></li>
                            <li><a href="<?php echo $this->url('frontend/user/squads'); ?>"><?php echo $this->translate('Squads'); ?></a></li>
                            <li class="divider"></li>
                            <li><a href="<?php echo $this->url('frontend/logout'); ?>"><?php echo $this->translate('Logout'); ?></a></li>
                        </ul>
                    </li>
                    <li><a href="<?php echo $this->url(null, array('locale' => 'de'), true); ?>"><img src="/images/frontend/icons/languages/de.png" /></a></li>
                    <li><a href="<?php echo $this->url(null, array('locale' => 'en'), true); ?>""><img src="/images/frontend/icons/languages/us.png" /></a></li>
                    <li class="label-primary"><a target="_blank" href="#">Buy me a Coffee? <span class="fa fa-coffee"></span></a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
    <div class="container">
        <div class="main-content">
            <?php echo $this->flashmessenger()->render(); ?>
            <?php echo $this->content; ?>
        </div>
        <hr>
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-unstyled">
                        <li class="pull-right"><a href="#top">Back to top</a></li>
                    </ul>
                    <p>Blabla maybe some hints to Bohemia Interactive Arma blabla</p>
                    <p>Based on <a href="http://getbootstrap.com" rel="nofollow">Bootstrap</a>. Icons from <a href="http://fortawesome.github.io/Font-Awesome/" rel="nofollow">Font Awesome</a>. Web fonts from <a href="http://www.google.com/webfonts" rel="nofollow">Google</a>.</p>
                    <p>Created with <span class="fa fa-heart"></span></p>
                </div>
            </div>
        </footer>
    </div>
    <!-- container end -->
    <!-- JS TIME! -->
    <?php echo $this->headscript(); ?>
    <?php echo $this->inlinescript(); ?>
</body>
</html>