<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Auth\Module'                         => __DIR__ . '/Module.php',
  'Auth\Acl\Acl'                        => __DIR__ . '/src/Auth/Acl/Acl.php',
  'Auth\Controller\Plugin\hasAccess'    => __DIR__ . '/src/Auth/Controller/Plugin/hasAccess.php',
  'Auth\Controller\Plugin\requireLogin' => __DIR__ . '/src/Auth/Controller/Plugin/requireLogin.php',
  'Auth\Controller\Plugin\setAccess'    => __DIR__ . '/src/Auth/Controller/Plugin/setAccess.php',
  'Auth\Entity\Benutzer'                => __DIR__ . '/src/Auth/Entity/Benutzer.php',
  'Auth\Entity\Permission'              => __DIR__ . '/src/Auth/Entity/Permission.php',
  'Auth\Entity\Resource'                => __DIR__ . '/src/Auth/Entity/Resource.php',
  'Auth\Entity\Role'                    => __DIR__ . '/src/Auth/Entity/Role.php',
  'Auth\Factory\AuthorizeFactory'       => __DIR__ . '/src/Auth/Factory/AuthorizeFactory.php',
  'Auth\Factory\hasAccessFactory'       => __DIR__ . '/src/Auth/Factory/hasAccessFactory.php',
  'Auth\Factory\requireLoginFactory'    => __DIR__ . '/src/Auth/Factory/requireLoginFactory.php',
  'Auth\Factory\setAccessFactory'       => __DIR__ . '/src/Auth/Factory/setAccessFactory.php',
  'Auth\Repository\Benutzer'            => __DIR__ . '/src/Auth/Repository/Benutzer.php',
  'Auth\Repository\Role'                => __DIR__ . '/src/Auth/Repository/Role.php',
  'Auth\View\Helper\hasAccess'          => __DIR__ . '/src/Auth/View/Helper/hasAccess.php',
  'Auth\Form\Account'                   => __DIR__ . '/src/Auth/Form/Account.php',
  'Auth\Form\Account\Fieldset\ResetPassword'                   => __DIR__ . '/src/Auth/Form/Fieldset/ResetPassword.php',
);
