<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Frontend\Squads\Module'                           => __DIR__ . '/Module.php',
  'Frontend\Squads\Controller\SquadMemberController' => __DIR__ . '/src/Frontend/Squads/Controller/SquadMemberController.php',
  'Frontend\Squads\Controller\SquadsController'      => __DIR__ . '/src/Frontend/Squads/Controller/SquadsController.php',
  'Frontend\Squads\Controller\SquadXmlController'    => __DIR__ . '/src/Frontend/Squads/Controller/SquadXmlController.php',
  'Frontend\Squads\Entity\Member'                    => __DIR__ . '/src/Frontend/Squads/Entity/Member.php',
  'Frontend\Squads\Entity\Squad'                     => __DIR__ . '/src/Frontend/Squads/Entity/Squad.php',
  'Frontend\Squads\Form\Filter\Squad'                => __DIR__ . '/src/Frontend/Squads/Form/Filter/Squad.php',
  'Frontend\Squads\Form\Member'                      => __DIR__ . '/src/Frontend/Squads/Form/Member.php',
  'Frontend\Squads\Form\MemberFieldset'              => __DIR__ . '/src/Frontend/Squads/Form/MemberFieldset.php',
  'Frontend\Squads\Form\Squad'                       => __DIR__ . '/src/Frontend/Squads/Form/Squad.php',
  'Frontend\Squads\Service\SquadImageService'        => __DIR__ . '/src/Frontend/Squads/Service/SquadImageService.php',
  'Frontend\Squads\Service\SquadImageServiceFactory' => __DIR__ . '/src/Frontend/Squads/Service/SquadImageServiceFactory.php',
);
