<div class="jumbotron">
    <h1><?php echo $this->translate('FRONTEND_STARTSEITE_HEADING'); ?></h1>
    <p><?php echo $this->translate('FRONTEND_STARTSEITE_SUBHEADING'); ?></p>
    <ul class="list-group">
        <li class="list-group-item">
            <span class="text-success fa fa-check-square-o"></span> <?php echo $this->translate('FRONTEND_STARTSEITE_LIST_FREE'); ?>
        </li>
        <li class="list-group-item">
            <span class="text-success fa fa-check-square-o"></span> <?php echo $this->translate('FRONTEND_STARTSEITE_LIST_TIME'); ?>
        </li>
        <li class="list-group-item">
            <span class="text-success fa fa-check-square-o"></span> <?php echo $this->translate('FRONTEND_STARTSEITE_LIST_SQUADS'); ?>
        </li>
        <li class="list-group-item">
            <span class="text-success fa fa-check-square-o"></span> <?php echo $this->translate('FRONTEND_STARTSEITE_LIST_HOSTING'); ?>
        </li>
        <li class="list-group-item">
            <span class="text-success fa fa-check-square-o"></span> <?php echo $this->translate('FRONTEND_STARTSEITE_LIST_XML'); ?>
        </li>
        <li class="list-group-item">
            <span class="text-success fa fa-check-square-o"></span> <?php echo $this->translate('FRONTEND_STARTSEITE_LIST_CONVERT'); ?>
        </li>
        <li class="list-group-item">
            <span class="text-success fa fa-check-square-o"></span> <?php echo $this->translate('FRONTEND_STARTSEITE_LIST_SUPPORT'); ?>
        </li>
        <li class="list-group-item">
            <span class="text-success fa fa-check-square-o"></span> <?php echo $this->translate('FRONTEND_STARTSEITE_LIST_NOADS'); ?>
        </li>
    </ul>
    <?php if( $this->identity() ): ?>
        <p><a href="<?php echo $this->url('frontend/user/squads/create'); ?>" class="btn btn-primary btn-lg"> <?php echo $this->translate('FRONTEND_STARTSEITE_BUTTON_START'); ?></a></p>
    <?php else: ?>
        <p><a href="#ex1" rel="modal:open" class="btn btn-primary btn-lg"> <?php echo $this->translate('FRONTEND_STARTSEITE_BUTTON_START'); ?></a></p>
    <?php endif; ?>
</div>

