<div class="jumbotron">
    <h1><?php echo $this->translate('Create your own Squad XML files within 5 Minutes!'); ?></h1>
    <p><?php echo $this->translate('This website is <u>non official</u> from Bohemia Interactive - This is a private website i programmed to help you creating Squad Files for Arma based games.'); ?></p>
    <ul class="list-group">
        <li class="list-group-item">
            <span class="text-success fa fa-check-square-o"></span> 100% free
        </li>
        <li class="list-group-item">
            <span class="text-success fa fa-check-square-o"></span> Creating a full Clan Squad File only take about 5 minutes!
        </li>
        <li class="list-group-item">
            <span class="text-success fa fa-check-square-o"></span> Add/Manage unlimited Squads
        </li>
        <li class="list-group-item">
            <span class="text-success fa fa-check-square-o"></span> We host your squad files - you get a link for each of your Squads
        </li>
        <li class="list-group-item">
            <span class="text-success fa fa-check-square-o"></span> Automatic generation of squad.xml, squad.dtd and squad.paa files
        </li>
        <li class="list-group-item">
            <span class="text-success fa fa-check-square-o"></span> Uploaded Images are converted for the Arma Gameserver (you can Upload PNG,GIF,JPG Images)
        </li>
        <li class="list-group-item">
            <span class="text-success fa fa-check-square-o"></span> Work with following Bohemia Interactive Games: Arma, Arma 2, Arma 2 Combined Operations, Arma 3
        </li>
        <li class="list-group-item">
            <span class="text-success fa fa-check-square-o"></span> No Ads!
        </li>
    </ul>
    <p><a href="#ex1" rel="modal:open" class="btn btn-primary btn-lg">Create my first Squad!</a></p>
</div>

