<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Frontend\Startseite\Module'                          => __DIR__ . '/Module.php',
  'Frontend\Startseite\Controller\StartseiteController' => __DIR__ . '/src/Frontend/Startseite/Controller/StartseiteController.php',
);
