<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Frontend\Impressum\Module'                          => __DIR__ . '/Module.php',
  'Frontend\Impressum\Controller\ImpressumController' => __DIR__ . '/src/Frontend/Impressum/Controller/ImpressumController.php',
);
