<div id="ex1" style="display:none;">
    <?php
    $this->loginForm = new \Frontend\Login\Form\Login();
    $this->registerForm = new \Frontend\Login\Form\Register();
    ?>
    <?php $this->headtitle($this->translate('Login')); ?>
    <?php echo $this->formErrors( $this->registerForm ); ?>
    <?php echo $this->formErrors( $this->loginForm ); ?>
    <div class="page-header">
        <h1><?php echo $this->translate('FRONTEND_LOGIN_TITLE'); ?></h1>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <div class="well bs-component">
                <legend><?php echo $this->translate('FRONTEND_LOGIN_LABEL_LOGIN'); ?></legend><br />
                <?php $this->loginForm->setAttribute('action', $this->url('frontend/login'))->prepare(); ?>
                <?php echo $this->form()->openTag($this->loginForm); ?>
                <fieldset>
                    <div class="form-group">
                        <?php echo $this->formLabel($this->loginForm->get('email') );?>
                        <div class="col-lg-12">
                            <?php echo $this->formEmail( $this->loginForm->get('email') );?>
                        </div>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formLabel($this->loginForm->get('password') );?>
                        <div class="col-lg-12">
                            <?php echo $this->formInput($this->loginForm->get('password'));?>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-12">
                            <?php echo $this->formSubmit($this->loginForm->get('submit'));?>
                        </div>
                    </div>
                </fieldset>
                <?php echo $this->form()->closeTag();?>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="well bs-component">
                <legend><?php echo $this->translate('FRONTEND_LOGIN_LABEL_REGISTER'); ?></legend><br />
                <?php $this->registerForm->setAttribute('action', $this->url('frontend/register'))->prepare(); ?>
                <?php echo $this->form()->openTag($this->registerForm); ?>
                <fieldset>
                    <div class="form-group">
                        <?php echo $this->formLabel($this->registerForm->get('username') );?>
                        <div class="col-lg-12">
                            <?php echo $this->formInput( $this->registerForm->get('username') );?>
                        </div>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formLabel($this->registerForm->get('email') );?>
                        <div class="col-lg-12">
                            <?php echo $this->formInput( $this->registerForm->get('email') );?>
                        </div>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formLabel($this->registerForm->get('password') );?>
                        <div class="col-lg-12">
                            <?php echo $this->formInput($this->registerForm->get('password'));?>
                            <?php echo $this->formInput($this->registerForm->get('password2'));?>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-12">
                            <?php echo $this->formSubmit($this->registerForm->get('submit'));?>
                        </div>
                    </div>
                </fieldset>
                <?php echo $this->form()->closeTag();?>
            </div>
        </div>
    </div>
</div>