<div class="page-header">
    <h1 id="type">
        <?php if( $this->squad->getLogo() ): ?>
            <img width="64" height="64" src="<?php echo $this->basePath( $squad->getSquadLogo() ); ?>" class="img-circle" />
        <?php endif; ?>
        »<em><?php echo $this->escapeHtml( $this->squad->getTag() ); ?></em>«
        <?php echo $this->escapeHtml( $this->squad->getName() ); ?>
    </h1>
</div>
<script>
    function add_member() {
        var currentCount = $('form > fieldset > fieldset').length;
        var template = $('form > fieldset > span').data('template');
        template = template.replace(/__index__/g, currentCount);
        template = $(template).hide();
        $('form > fieldset').prepend(template);
        $('form > fieldset > fieldset').eq(0).slideDown();

        return false;
    }
</script>
<div class="well">
    <?php $form->prepare(); ?>
    <?php echo $this->form()->openTag($form); ?>
    <a href="<?php echo $this->url('frontend/user/squads'); ?>" class="btn btn-danger"><?php echo $this->translate('Back'); ?></a>
    <button type="submit" class="btn btn-success"><?php echo $this->translate('Save'); ?></button>
    <div class="btn btn-primary" onclick="return add_member()">Add a new Member</div>
    <hr>
    <?php echo $this->formCollection( $this->form->get('members') ); ?>
    <hr>
    <a href="<?php echo $this->url('frontend/user/squads'); ?>" class="btn btn-danger"><?php echo $this->translate('Back'); ?></a>
    <button type="submit" class="btn btn-success"><?php echo $this->translate('Save'); ?></button>
    <?php echo $this->form()->closeTag($form); ?>
</div>
