<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Application\Module'                                     => __DIR__ . '/Module.php',
  'Application\Factory\Controller\Plugin\PaginatorFactory' => __DIR__ . '/src/Application/Factory/Controller/Plugin/PaginatorFactory.php',
  'Application\Repository\BaseEntityRepository'            => __DIR__ . '/src/Application/Repository/BaseEntityRepository.php',
  'Application\View\Helper\DateFormat'                     => __DIR__ . '/src/Application/View/Helper/DateFormat.php',
  'Application\View\Helper\FlashMessenger'                 => __DIR__ . '/src/Application/View/Helper/FlashMessenger.php',
  'Application\View\Helper\formErrors'                     => __DIR__ . '/src/Application/View/Helper/formErrors.php',
  'Application\View\Helper\Translate'                      => __DIR__ . '/src/Application/View/Helper/Translate.php',
  'Application\View\Helper\ServerUrl'                      => __DIR__ . '/src/Application/View/Helper/ServerUrl.php',
);
