<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Frontend\Api\Module'                            => __DIR__ . '/Module.php',
  'Frontend\Api\Controller\AbstractJsonController' => __DIR__ . '/src/Frontend/Api/Controller/AbstractJsonController.php',
  'Frontend\Api\Controller\ApiController'          => __DIR__ . '/src/Frontend/Api/Controller/ApiController.php',
  'Frontend\Api\Entity\Key'                        => __DIR__ . '/src/Frontend/Api/Entity/Key.php',
  'Frontend\Api\Repository\Key'                    => __DIR__ . '/src/Frontend/Api/Repository/Key.php',
  'Frontend\Api\Response\ApiResponse'              => __DIR__ . '/src/Frontend/Api/Response/ApiResponse.php',
  'Frontend\Api\v1\Controller\MembersController'   => __DIR__ . '/src/Frontend/Api/v1/Controller/MembersController.php',
  'Frontend\Api\v1\Controller\SquadsController'    => __DIR__ . '/src/Frontend/Api/v1/Controller/SquadsController.php',
);
