<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Frontend\Application\Module'                                => __DIR__ . '/Module.php',
  'Frontend\Application\Controller\AbstractFrontendController' => __DIR__ . '/src/Frontend/Application/Controller/AbstractFrontendController.php',
  'Frontend\Application\Form\AbstractFrontendFieldset'         => __DIR__ . '/src/Frontend/Application/Form/AbstractFrontendFieldset.php',
  'Frontend\Application\Form\AbstractFrontendForm'             => __DIR__ . '/src/Frontend/Application/Form/AbstractFrontendForm.php',
  'Frontend\Application\View\Helper\formCollection'            => __DIR__ . '/src/Frontend/Application/View/Helper/formCollection.php',
);
