<?php $this->headtitle('Create new Squad'); ?>
<div class="page-header">
    <h1 id="type"><?php echo $this->translate('Create new Squad'); ?></h1>
</div>
<?php $form->prepare(); ?>
<?php echo $this->form()->openTag($form); ?>
    <fieldset>
        <div class="form-group">
            <?php echo $this->formLabel($this->form->get('tag')); ?>
            <div class="col-lg-1">
                <?php echo $this->formText($this->form->get('tag')); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel( $this->form->get('name') ); ?>
            <div class="col-lg-10">
                <?php echo $this->formText( $this->form->get('name') ); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel( $this->form->get('title') ); ?>
            <div class="col-lg-10">
                <?php echo $this->formText( $this->form->get('title') ); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel( $this->form->get('email') ); ?>
            <div class="col-lg-10">
                <?php echo $this->formEmail( $this->form->get('email') ); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formElementErrors($this->form->get('logo')); ?>
            <?php echo $this->formLabel( $this->form->get('logo') ); ?>
            <div class="col-lg-10">
                <?php echo $this->formFile( $this->form->get('logo') ); ?>
                <p><?php echo $this->translate('Notice! Currently the Arma Gameserver receive your Squad Logo non transparent! I work hard to get this fixed!'); ?></p>
            </div>
        </div>


        <div class="form-group">
            <div class="col-lg-10 col-lg-offset-2">
                <a class="btn btn-danger" href="<?php echo $this->url('frontend/user/squads'); ?>">Cancel</a>
                <button type="submit" class="btn btn-primary"><?php echo $this->translate('Create my awesome Squad!'); ?></button>
            </div>
        </div>
    </fieldset>
<?php echo $this->form()->closeTag($form); ?>