<div class="page-header">
    <h1 id="type"><?php echo $this->translate('Create new Squad File'); ?></h1>
</div>
<form class="form-horizontal">
    <fieldset>
        <div class="form-group">
            <?php echo $this->formLabel($this->form->get('tag')); ?>
            <div class="col-lg-1">
                <?php echo $this->formText($this->form->get('tag')); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel( $this->form->get('name') ); ?>
            <div class="col-lg-10">
                <?php echo $this->formText( $this->form->get('name') ); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel( $this->form->get('title') ); ?>
            <div class="col-lg-10">
                <?php echo $this->formText( $this->form->get('title') ); ?>
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-10 col-lg-offset-2">
                <button class="btn btn-default"><a href="<?php echo $this->url('frontend/user/squads'); ?>">Cancel</a></button>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </fieldset>
</form>