<div class="page-header">
    <h1 id="type"><?php echo $this->translate('Edit Squad'); ?></h1>
</div>
<?php $form->prepare(); ?>
<?php echo $this->form()->openTag($form); ?>
    <fieldset>
        <div class="form-group">
            <?php echo $this->formLabel($this->form->get('tag')); ?>
            <div class="col-lg-1">
                <?php echo $this->formText($this->form->get('tag')); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel( $this->form->get('name') ); ?>
            <div class="col-lg-10">
                <?php echo $this->formText( $this->form->get('name') ); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel( $this->form->get('title') ); ?>
            <div class="col-lg-10">
                <?php echo $this->formText( $this->form->get('title') ); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel( $this->form->get('email') ); ?>
            <div class="col-lg-10">
                <?php echo $this->formEmail( $this->form->get('email') ); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel( $this->form->get('logo') ); ?>
            <div class="col-lg-10">
                <?php echo $this->formFile( $this->form->get('logo') ); ?><br />
                <?php if( $this->form->getObject()->getLogo() ): ?>
                    <?php echo $this->translate('Current Squad Image'); ?>:
                    <img src="<?php echo $this->form->getObject()->getSquadLogo(64); ?>" />
                <?php endif; ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-10 col-lg-offset-2">
                <button type="submit" class="btn btn-primary"><?php echo $this->translate('Edit my awesome Squad!'); ?></button>
                <a class="btn btn-danger" href="<?php echo $this->url('frontend/user/squads'); ?>">Cancel</a>
            </div>
        </div>
    </fieldset>
<?php echo $this->form()->closeTag($form); ?>