<?php $this->headtitle('Edit Squad'); ?>
<?php echo $this->formErrors( $this->form ); ?>
<div class="page-header">
    <h1 id="type"><?php echo $this->translate('Edit Squad'); ?></h1>
</div>
<?php $form->prepare(); ?>
<?php echo $this->form()->openTag($form); ?>
    <fieldset>
        <div class="form-group">
            <?php echo $this->formLabel($this->form->get('tag')); ?>
            <div class="col-lg-1">
                <?php echo $this->formText($this->form->get('tag')); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel( $this->form->get('name') ); ?>
            <div class="col-lg-10">
                <?php echo $this->formText( $this->form->get('name') ); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel( $this->form->get('title') ); ?>
            <div class="col-lg-10">
                <?php echo $this->formText( $this->form->get('title') ); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel( $this->form->get('homepage') ); ?>
            <div class="col-lg-10">
                <?php echo $this->formUrl( $this->form->get('homepage') ); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel( $this->form->get('email') ); ?>
            <div class="col-lg-10">
                <?php echo $this->formEmail( $this->form->get('email') ); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel( $this->form->get('logo') ); ?>
            <div class="col-lg-10">
                <?php echo $this->formFile( $this->form->get('logo') ); ?>
                <?php if( $this->form->getObject()->getLogo() ): ?>
                    <div class="well">
                        <div class="row">
                            <div class="col-xs-12 col-sm-8">
                                <p class="text-primary"><?php echo $this->translate('Current Squad Image'); ?>:</p>
                                <hr>
                                <div class="checkbox">
                                    <?php echo $this->formCheckbox( $this->form->get('deleteLogo') ); ?>
                                    <?php echo $this->formLabel($this->form->get('deleteLogo')); ?>
                                </div>
                                <br /><br />
                            </div>
                            <div class="col-xs-12 col-sm-4">
                                <img class="img-responsive" style="border: 1px solid rgba(0, 0, 0, 0.1)" src="<?php echo $this->basepath( $this->form->getObject()->getSquadLogo() ); ?>" />
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-lg-10 col-lg-offset-2">
                <a class="btn btn-danger" href="<?php echo $this->url('frontend/user/squads'); ?>">Cancel</a>
                <button type="submit" class="btn btn-primary"><?php echo $this->translate('Edit my awesome Squad!'); ?></button>
            </div>
        </div>
    </fieldset>
<?php echo $this->form()->closeTag($form); ?>