<?php $this->headtitle('My Squads'); ?>
<div class="alert alert-dismissable alert-warning">
    <h4>Update your ingame squad url!</h4>
    <p>
        In order to increase your privacy your squad urls are now randomized to prevent easy
        "try and error" access to your squad xml files and grabbing (in case you have set one) member email addresses.
        <b>Until June 06/20/2014</b> you can still access your squad xml files with the old url, after that date
        all old urls are tossed and won't work anymore.<br />
        <br />
        Cheers ins0!
    </p>
</div>
<div class="page-header">
    <h1 id="type"><?php echo $this->translate('My Squads'); ?></h1>
</div>

<a class="btn btn-success btn-sm" href="<?php echo $this->url('frontend/user/squads/create') ?>">
    <?php echo $this->translate('Create new Squad-File'); ?>
</a>
<br />
<br />
<?php foreach($this->squads as $squad ): ?>
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <div class="col-xs-12 col-sm-1 text-center">
                    <?php if( $squad->getLogo() ): ?>
                        <img width="64" height="64" style="border: 1px solid rgba(0, 0, 0, 0.1)" src="<?php echo $this->basePath( $squad->getSquadLogo() ); ?>" class="img-circle" />
                    <?php else: ?>
                        <span style="font-size: 64px" class="fa fa-times-circle"></span>
                    <?php endif; ?>
                </div>
                <div class="col-xs-12 col-sm-7">
                    <h3 class="list-group-item-heading">
                        »<em><?php echo $this->escapeHtml( $squad->getTag() ); ?></em>«
                        <b><?php echo $this->escapeHtml( $squad->getName() ); ?></b>
                    </h3>
                    <p class="list-group-item-text">
                        <?php echo $this->escapeHtml( $squad->getTitle() ); ?>
                    </p>
                </div>
                <div class="col-xs-12 col-sm-4 text-right-not-xs">
                    <hr class="visible-xs">
                    <?php echo count($squad->getMembers()) . ' ' . $this->translatePlural( 'Member', 'Members', count($squad->getMembers()) ); ?><br />
                    <?php echo $this->escapeHtml( $squad->getEmail() ); ?>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <input type="text" class="form-control" value="<?php echo 'http://' . $_SERVER['SERVER_NAME'] . ($this->url('frontend/user/squads/xml', array('id' => $squad->getPrivateId()))); ?>" id="inputDefault">
            <hr>
            <?php if($this->hasAccess('frontend/squads/create') ): ?>
                <a class="btn btn-primary btn-sm" href="<?php echo $this->url('frontend/user/squads/edit', array('id'=>$squad->getId())) ?>">
                    <span class="fa fa-edit"></span>
                    <?php echo $this->translate('Edit'); ?>
                </a>
                <a class="btn btn-primary btn-sm" href="<?php echo $this->url('frontend/user/squads/member', array('id'=>$squad->getId())) ?>">
                    <span class="fa fa-users"></span>
                    <?php echo $this->translate('Members'); ?>
                </a>
            <?php endif; ?>
            <?php if($this->hasAccess('frontend/squads/delete') ): ?>
                <a class="btn btn-danger btn-sm delete-confirm" href="<?php echo $this->url('frontend/user/squads/delete', array('id'=>$squad->getId())) ?>">
                    <span class="fa fa-minus-circle"></span>
                    <?php echo $this->translate('Delete'); ?>
                </a>
            <?php endif; ?>
        </div>
    </div>
<?php endforeach; ?>