<?php $this->headtitle('Support this Service'); ?>
<div class="page-header">
    <h1 id="type">Help Keep This Service Alive</h1>
</div>
<p class="text-justify">
    This Service is completely free of any charge. Help to keep this project alive would be very welcome.<br />
</p>
<hr>
<br />
<h2>Give Feedback!</h2>
<blockquote>
    <p>With <a target="_blank" href="http://forums.bistudio.com/showthread.php?178233-Online-Squad-xml-Editor-WebApp">your feedback</a> we can make this site even better or <a href="https://github.com/ins0/armasquads/issues">report a bug or request a new feature</a>.</p>
    <p>Of course you can ping me by mail: <a href="mailto:info@armasquads.com">info@armasquads.com</a></p>
</blockquote>
<br />
<h2>Support with a small donation</h2>
<blockquote>
    <p>
        This server and domains needs payed every month, so spend a few bugs helps directly to keep this service alive.<br />
        Or maybe you just want to say thanks, spend me a coffee or just a little present for the hole time i spend into this project :)<br />
        <br />
        <?php if($this->plugin('translate')->getTranslator()->getLocale() == 'de_DE') : ?>
            <a target="_blank" href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=9RXCMSXR8DAWW">
                <img alt="" border="0" src="https://www.paypalobjects.com/de_DE/DE/i/btn/btn_donateCC_LG.gif" />
            </a>
        <?php else: ?>
            <a target="_blank" href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=3WR4JVHJKM8HA">
                <img alt="" border="0" src="https://www.paypalobjects.com/de_DE/DE/i/btn/btn_donateCC_LG.gif" />
            </a>
        <?php endif; ?>
    </p>
</blockquote>
<hr>
<h3 class="text-center">
    <b>Thanks for your support!</b><br />
    <br />
    Here are some stats about this Project. Stats are tracked via Git.
</h3>
<hr/>
<br />
<div class="row">
    <div class="col-xs-12 col-sm-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Time spend in editor (overall time)</h3>
            </div>
            <div class="panel-body text-center">
                ~ <?php echo number_format($this->total_time / 60, 2); ?> Hours
            </div>
        </div>
        <ul class="list-group">
            <?php foreach($this->data as $key => $value ): ?>
            <li class="list-group-item">
                <span class="badge"><b><?php echo $this->escapeHtml($value); ?></b></span>
                &nbsp;&nbsp;&nbsp;<?php echo $this->escapeHtml($key); ?>
            </li>
            <?php endforeach; ?>
        </ul>
        <div class="well">
            * commits are changes against this project. one commit can include one or more changes.
        </div>
    </div>
    <div class="col-xs-12 col-sm-6">
        <img class="img-responsive" src="<?php echo $this->basePath('images/frontend/stats.jpg'); ?>" /><br />
    </div>
</div>