<?php $this->headtitle('Dashboard'); ?>
<div class="page-header">
    <h1 id="type"><?php echo sprintf($this->translate('Welcome back, <b>%s</b>!'), $this->escapeHtml($this->identity()->getUsername())); ?></h1>
</div>
<div class="well well-lg">
    <h4 class="text-center"><b>Choose your action from the menu in the upper right corner.</b></h4>
    <hr>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Armasquads.com is now full open source!</h3>
        </div>
        <div class="panel-body">
            Armasquads.com and it source files are now full open source.<br />
            View all files on GitHub - view the changelog, comment, discuss, flame code...fork...enjoy<br />
            <br />
            <a href="https://github.com/ins0/armasquads" target="_blank"><strong><u>https://github.com/ins0/armasquads</u></strong></a>
            <br /><br />
        </div>
    </div>
</div>
<hr>
<div class="panel panel-default">
    <div class="panel-heading">Changelog</div>
    <div class="panel-body">
        <div class="panel-group" id="accordion">
            <br />
            <a href="https://github.com/ins0/armasquads/commits/master" target="_blank"><strong><u>CHANGELOG NOW ON GITHUB</u></strong></a>
        </div>
    </div>
</div>
