<?php $this->headtitle('Dashboard'); ?>
<div class="page-header">
    <h1 id="type"><?php echo sprintf($this->translate('Welcome back, <b>%s</b>!'), $this->escapeHtml($this->identity()->getUsername())); ?></h1>
</div>
<div class="well well-lg">
    <h4 class="text-center"><b>Choose your action from the menu in the upper right corner.</b></h4>
    <hr>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Sad news?</h3>
        </div>
        <div class="panel-body">
            As you might allready see - today i added ads on this website. It is a hard step as i hate ads at all but i
            will try to explain why i take this changes.<br />
            <br />
            Armasquads.com is now ~1 year online and is growing every day. I love to see how this project went from a
            small side project to something bigger and to a tool that is usefull for so many awesome squads/users.<br />
            <br />
            I don't want to make profit out of this project but i would love to achieve that the monthly costs, to
            running this project, are covered.<br />
            <hr>
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <td><b>Description</b></td>
                        <td><b>Yearly costs</b></td>
                        <td><b>Monthly costs</b></td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Server</td>
                        <td>108 $ (~15% from 720$ - as i use this server also for other things then this project)</td>
                        <td>9 $</td>
                    </tr>
                    <tr>
                        <td>Server Domain SSL Certs</td>
                        <td>18$</td>
                        <td>1,50 $</td>
                    </tr>
                    <tr>
                        <td>Domains</td>
                        <td>19,75 $</td>
                        <td>1,65 $</td>
                    </tr>
                </tbody>
                <tr>
                    <td><b>Total cost</b></td>
                    <td><b>145,75 $/Year</b></td>
                    <td><b>12,15 $/Month</b></td>
                </tr>
            </table>
            <br />
            In this one year i received 8 donations. I would like to thank here the following people:<br />
            <br />
            <ul>
                <li>Florian N. (9,31 $)</li>
                <li>Dennis V. (4,99 $)</li>
                <li>Lukas L. (1,3 $)</li>
                <li>Thijs G. (5 $)</li>
                <li>Aleksandra K. (2,84 $)</li>
                <li>Rico Z. (4,99 $)</li>
                <li>Matthias R. (10,38 $)</li>
                <li>David B. (9,31 $)</li>
            </ul>
            <small>(Donations after paypal fee)</small><br />
            <br>
            So in the current year there are <b>48,12 $</b> donations in total. Calculated with the montly costs this donations
            covers 33% of it's monthly cost.<br />
            <br />
            Every day this project needs more resources of CPU/RAM and Storage (you guys are awesome - this shows me that this project runs and is usefull for you).<br/>
            I will try to get the remaining 77% in with ads.<br />
            <br />
            If you don't donate (which is totally fine!) - you may click on the ads and help to keep this project alive too.<br />
            I hope you understand why i running now ads on this site - if you like to give feedback - tweet me on twitter - <a href="https://twitter.com/racecore" target="_blank">@racecore</a><br />
            <br /><br />
            I would like to thank all of you - using this tool / make video tutorials on youtube / suggest on forums.
            <br />
            <br />
            <b>ins0</b>


            <br /><br />
        </div>
    </div>
</div>
<hr>
<div class="panel panel-default">
    <div class="panel-heading">Changelog</div>
    <div class="panel-body">
        <div class="panel-group" id="accordion">
            <br />
            <a href="https://github.com/ins0/armasquads/releases" target="_blank"><strong><u>CHANGELOG NOW ON GITHUB</u></strong></a>
        </div>
    </div>
</div>
